# server
server.port=8080
# h2 (dev)
spring.datasource.url=jdbc:h2:file:./subtrack-dev
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
# jwt
app.jwt.secret=change-me-in-prod-at-least-32-chars-long-secret
app.jwt.expiration-ms=86400000
# security
app.jwt.refresh-expiration-days=30
spring.task.scheduling.enabled=true

# mailtrap smtp (dev)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e94bb87b9ae986
spring.mail.password=71bd571b5c5ce9
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# app config
app.mail.from=noreply@subtrack.dev
app.frontend.url=http://localhost:5173


logging.level.org.springframework.security=DEBUG
logging.level.com.subtrack=DEBUG
logging.level.org.hibernate=DEBUG
spring.jpa.open-in-view=false
