# activated via SPRING_PROFILES_ACTIVE=prod

# postgresql ? values injected by Render via env vars
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

# jwt
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-days=30

# smtp
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_FROM}

# urls
app.frontend.url=${FRONTEND_URL}

# logs
logging.level.org.springframework.security=WARN
logging.level.com.subtrack=INFO
logging.level.org.hibernate=WARN
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.task.scheduling.enabled=true